name: Generate ASCII file

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Execute ASCII artwork
      run: ./ascii-script.sh