name: Generate ASCII file

on: 
  push:
  workflow_dispatch: 

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Execute ASCII artwork
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh