name: My Matrix Workflow

on: 
  workflow_dispatch: 

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Docker Run
      run: docker run ${{ matrix.image }}